### PR TITLE
Improve robustness

### PR DESCRIPTION
**Pull request by CloCkWeRX**

### CODE REVIEW

**Comment by henare** [comment]
I'm getting really wonky data running this:

selection_001

Are you seeing clean data on your machine?

**Comment by CloCkWeRX** [comment]
I wasn't looking via morph-cli; just fixing up the errors. Happy to take another look.

**Comment by CloCkWeRX** [comment]
Alright, it's a bit better now.
The problem is the output format is randomly swapping between two output styles. The original code was trying to cater for it, but I've decided to skip those as too hard.

**Comment by henare** [comment]
I'm just running it with `ruby scraper.rb` and having a look at the resulting SQLite database.

It's still got bad data in it for me:

selection_001

We need to fix that up for this to be merged.

**Comment by henare** [comment]
I'm still seeing missing data:

selection_001

Maybe clear out your database each time you test to make sure it's working properly.

**Pull request closed without merging**
