### PR TITLE
Repair Onkaparinga scraper.

### PR DESCRIPTION
**Pull request by emikulic**
Example output:

"council_reference"=>"145/1209/2015", "address"=>"725 (Sec 583 HP 106000) Chapel Hill Road, BLEWITT SPRINGS SA 5171", "description"=>"Amendment to approved Distillery Building (145/2121/2014) - increasing size and height of a new replacement building and change of floor plan to include tasting room and separate mill room", "info_url"=>"http://www.onkaparingacity.com/onka/living_here/planning_development/applications_for_public_comment.jsp", "comment_url"=>"mailto:mail@onkaparinga.sa.gov.au?Subject=Planning+application+145/1209/2015", "date_scraped"=>"2015-06-17", "on_notice_from"=>"Tuesday 02-Jun-2015", "on_notice_to"=>"Wednesday 17-Jun-2015"

### CODE REVIEW

**Comment by henare** [comment]
@emikulic The dates don't look like they're YYYY-MM-DD format. I'm not sure if this is a problem but can you please double-check and also create a Morph.io scraper from your fork so it's easy to check?

**Comment by emikulic** [comment]
Done: https://morph.io/emikulic/onkaparinga

As for whether it's a problem, I can't tell. Sorry.

**Comment by henare** [comment]
@emikulic thanks!

Yes, those dates are currently being stored as strings so you'll need to `Date.parse(foo).to_s` or something.

**Comment by emikulic** [comment]
Done.

**Comment by henare** [comment]
Grr. Those addresses are going to be problematic :(

**Comment by emikulic** [comment]
Try now.

**Comment by henare** [comment]
Wow, nice work!

**Pull request merged**
